name: Auto Commit (Random Daily)

permissions:
  contents: write

on:
  schedule:
    - cron: "0 18 * * *"   # 01.00 WIB setiap hari
  workflow_dispatch:

jobs:
  auto_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Git
        run: |
          git config --local user.email "rezawalker02@gmail.com"
          git config --local user.name "walkerreza"

      - name: Generate random commit count
        id: random
        run: |
          MIN=9
          MAX=15
          COUNT=$((RANDOM % (MAX - MIN + 1) + MIN))
          echo "count=$COUNT" >> $GITHUB_OUTPUT
          echo "Today will commit $COUNT times"

      - name: Auto Commit Loop
        run: |
          for i in $(seq 1 ${{ steps.random.outputs.count }})
          do
            echo "Commit $i at $(date -u)" > LAST_UPDATED
            git add LAST_UPDATED
            git commit -m "Penghijauan #$i"
          done

      - name: Push
        run: git push
